config/routes.rb
Rails.application.routes.draw do

  get 'sitemap.:format' => 'home#sitemap'

  get 'sobre' => 'about_us#index', :as => 'about_us'
  get 'contato' => 'contact#index', :as => 'contact'
  post 'contato' => 'contact#contact_us', :as => 'contact_us'

  get 'imovel/:id/:estate/:city/:title' => 'look_real_estate#index', :as => 'look_real_estate_index'
  get 'imovel/codigo/:code' => 'look_real_estate#by_code', :as => 'look_real_estate_index_code'
  get 'imovel/proposta/:key' => 'look_real_estate#proposal', :as => 'look_real_estate_proposal'
  post 'imovel/solicitar-proposta' => 'look_real_estate#call_proposal', :as => 'look_real_estate_call_proposal'

  get 'procurar' => 'search#index', :as => 'search'
  get 'procurar/tipo/:name/:page' => 'search#type', :as => 'search_by_type'

  get 'locations/all-states' => 'application#load_states'
  get 'locations/search-cities/:state_id' => 'application#search_cities'
  get 'locations/search-cities-by-name/:q' => 'application#search_cities_by_name'
  get 'locations/search-neighborhoods/:q' => 'application#search_neighborhoods'
  get 'locations/search-neighborhoods-by-city/:city_id' => 'application#search_neighborhoods_by_city'
  get 'locations/search-postal-code/:postal_code' => 'application#search_postal_code'
  post 'news-letter/subscribe' => 'news_letters#subscribe', :as => 'subscribe'


  get 'manager' => 'manager_home#index'

  scope :manager do
    resources :real_estates do
      collection do
        post 'upload-pic', :to => 'real_estates#upload_pic', :as => 'upload_pic'
        delete 'delete-pic/:key', :to => 'real_estates#delete_pic', :as => 'delete_pic'
      end
    end

    resources :users do
      collection do
        get 'profile', :to => 'users#profile', :as => 'profile'
      end
    end

    resources :proposals do
      collection do
        get 'real-estate/:id', :to => 'proposals#real_estate', :as => 'real_estate'
        get 'send-proposal/:id', :to => 'proposals#send_proposal', :as => 'send_proposal'
      end
    end

    resources :cities, :neighborhoods, :news_letters

    get 'session' => 'session#index'
    post 'session/create' => 'session#create'
    get 'session/destroy' => 'session#destroy'
    post 'session/forget-password' => 'session#forget_password', :defaults => { :format => 'json' }
  end

  root 'home#index'


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    set_cities_with_real_estate

    set_last_real_estates 4
  end

  def sitemap

  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div id="header" class="carousel slide carousel-fade hidden-xs" data-ride="carousel">
  <div class="carousel-inner">
    <div class="item active" style="background-image: url(<%= image_path randomized_city_image %>);">
      <div class="carousel-caption">
        <h3>O Imóvel que você procura esta aqui...</h3>
        <p>Ache o imóvel que você deseja de forma simples e rápida.</p>
        <div class="property-btn">
          <a href="<%= search_path %>" class="btn btn-success btn-lg"><i class="fa fa-search"></i> Procurar</a>
        </div>
      </div>
    </div>
    <div class="item" style="background-image: url(<%= image_path randomized_city_image %>);">
      <div class="carousel-caption hidden-xs">
        <h3>Milhares de imóveis a um clique de você</h3>
        <p>Ache o imóvel que você deseja e entre em contato conosco. Teremos o prazer em atendê-lo.</p>
        <div class="property-btn">
          <a href="<%= contact_path %>" class="btn btn-success btn-lg"><i class="fa fa-phone"></i> Fale Conosco</a>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#header" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#header" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

<div id="service">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>A BUY IMÓVEIS TRAZ AS MELHORES OPORTUNIDADES PARA VOCÊ <small>Apartamentos, Casas, Lojas, Prédios comerciais, Studios e Muito mais...</small></h2>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="service-container">
          <div class="service-icon">
            <a href="#content"><i class="fa fa-home"></i></a>
          </div>
          <div class="service-content">
            <h3>Imóveis</h3>
            <p>Possuímos uma base com milhares de imóveis para ajudar você a encontrar o que deseja.</p>
          </div>
        </div>
      </div>
      <!-- break -->
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="service-container">
          <div class="service-icon">
            <a href="<%= search_path %>"><i class="fa fa-search"></i></a>
          </div>
          <div class="service-content">
            <h3>Simples e Rápido</h3>
            <p>Nosso site oferece uma forma simples e eficaz para você encontrar o seu imóvel.</p>
          </div>
        </div>
      </div>
      <!-- break -->
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="service-container">
          <div class="service-icon">
            <a href="<%= about_us_path %>#securanca"><i class="fa fa-shield"></i></a>
          </div>
          <div class="service-content">
            <h3>Segurança</h3>
            <p>Faça negócios com segurança tratando com quem entende do ramo imobiliário.</p>
          </div>
        </div>
      </div>
      <!-- break -->
      <div class="col-md-3 col-sm-6 col-xs-12">
        <div class="service-container">
          <div class="service-icon">
            <a href="<%= about_us_path %>#equipe"><i class="fa fa-users"></i></a>
          </div>
          <div class="service-content">
            <h3>equipe</h3>
            <p>Contamos com uma equipe altamente qualificada e com vários anos de experiência no mercado imobiliário.</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div id="content">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="heading-title">
          <h2>ÚLTIMOS IMÓVEIS</h2>
        </div>
      </div>
    </div>
    <div class="row">

      <% cache('general_real_estates_home', skip_digest: true) do %>
          <% @last_real_estates.each do |re| %>
              <div class="col-md-3 col-sm-6 col-xs-12">
                <div class="property-container">
                  <div class="property-image">
                    <% if re.real_estate_images.first.nil? %>
                        <a href="<%= url_real_estate_full re %>"><img src="<%= image_path 'sem-foto.jpg' %>" alt="Sem Foto"></a>
                    <% else %>
                        <a href="<%= url_real_estate_full re %>"><img src="<%= re.real_estate_images.first.url %>" alt="Foto <%= re.real_estate_images.first.label %>"></a>
                    <% end %>

                    <div class="property-price">
                      <h4><%= t("real_estate_type_#{re.rent_type}") %></h4>
                      <span>R$ <%= number_to_currency(re.price, :unit => '', :separator => ',', :delimiter => '.') %></span>
                    </div>
                  </div>
                  <div class="property-features">
                    <span><%= re.total_area %> m<sup>2</sup></span>
                    <span><%= re.bedrooms %> Dorm</span>
                    <span><%= re.bathrooms %> Suítes</span>
                  </div>
                  <div class="property-content">
                    <h4><a href="<%= url_real_estate_full re %>"><%= re.title %></a></h4>
                  </div>
                  <div class="property-footer">
                    <a href="<%= url_real_estate_full re %>#localizacao" title="Solicitar Proposta"><i class="fa fa-envelope"></i></a>
                  </div>
                </div>
              </div>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/sitemap.xml.erb
<?xml version="1.0" encoding="UTF-8"?>
 <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">

    <url>
        <loc>http://www.buyimoveis.com.br/</loc>
        <changefreq>daily</changefreq>
        <priority>0.5</priority>
    </url>

    <url>
        <loc>http://www.buyimoveis.com.br/procurar</loc>
        <changefreq>daily</changefreq>
        <priority>0.5</priority>
    </url>

    <url>
        <loc>http://www.buyimoveis.com.br/sobre</loc>
        <changefreq>monthly</changefreq>
        <priority>0.5</priority>
    </url>

    <url>
        <loc>http://www.buyimoveis.com.br/contato</loc>
        <changefreq>monthly</changefreq>
        <priority>0.5</priority>
    </url>



    <% RealEstate.where(:removed => false).each do |re| %>
    <url>
        <loc>http://www.buyimoveis.com.br<%= url_real_estate_full re %></loc>
        <changefreq>weekly</changefreq>
        <lastmod><%= re.updated_at.strftime '%Y-%m-%dT%H:%M:%SZ' %></lastmod>
        <priority>0.5</priority>


        <% re.real_estate_images.each do |img| %>
            <image:image>
                <image:loc><%= img.url %></image:loc>
                <image:title><%= img.label %></image:title>
                <image:caption><%= t("real_estate_type_#{re.rent_type}") %></image:caption>
                <image:geo_location><%= re.street %>, <%= re.neighborhood.name %> - <%= re.neighborhood.city.name %>/<%= re.neighborhood.city.state.name %></image:geo_location>
            </image:image>
        <% end %>

    </url>

    <url>
        <loc>http://www.buyimoveis.com.br<%= url_real_estate_code re.code %></loc>
        <changefreq>weekly</changefreq>
        <lastmod><%= re.updated_at.strftime '%Y-%m-%dT%H:%M:%SZ' %></lastmod>
        <priority>0.5</priority>
    </url>
    <% end %>

</urlset>