config/routes.rb
Rails.application.routes.draw do

  get 'sitemap.:format' => 'home#sitemap'

  get 'sobre' => 'about_us#index', :as => 'about_us'
  get 'contato' => 'contact#index', :as => 'contact'
  post 'contato' => 'contact#contact_us', :as => 'contact_us'

  get 'imovel/:id/:estate/:city/:title' => 'look_real_estate#index', :as => 'look_real_estate_index'
  get 'imovel/codigo/:code' => 'look_real_estate#by_code', :as => 'look_real_estate_index_code'
  get 'imovel/proposta/:key' => 'look_real_estate#proposal', :as => 'look_real_estate_proposal'
  post 'imovel/solicitar-proposta' => 'look_real_estate#call_proposal', :as => 'look_real_estate_call_proposal'

  get 'procurar' => 'search#index', :as => 'search'
  get 'procurar/tipo/:name/:page' => 'search#type', :as => 'search_by_type'

  get 'locations/all-states' => 'application#load_states'
  get 'locations/search-cities/:state_id' => 'application#search_cities'
  get 'locations/search-cities-by-name/:q' => 'application#search_cities_by_name'
  get 'locations/search-neighborhoods/:q' => 'application#search_neighborhoods'
  get 'locations/search-neighborhoods-by-city/:city_id' => 'application#search_neighborhoods_by_city'
  get 'locations/search-postal-code/:postal_code' => 'application#search_postal_code'
  post 'news-letter/subscribe' => 'news_letters#subscribe', :as => 'subscribe'


  get 'manager' => 'manager_home#index'

  scope :manager do
    resources :real_estates do
      collection do
        post 'upload-pic', :to => 'real_estates#upload_pic', :as => 'upload_pic'
        delete 'delete-pic/:key', :to => 'real_estates#delete_pic', :as => 'delete_pic'
      end
    end

    resources :users do
      collection do
        get 'profile', :to => 'users#profile', :as => 'profile'
      end
    end

    resources :proposals do
      collection do
        get 'real-estate/:id', :to => 'proposals#real_estate', :as => 'real_estate'
        get 'send-proposal/:id', :to => 'proposals#send_proposal', :as => 'send_proposal'
      end
    end

    resources :cities, :neighborhoods, :news_letters

    get 'session' => 'session#index'
    post 'session/create' => 'session#create'
    get 'session/destroy' => 'session#destroy'
    post 'session/forget-password' => 'session#forget_password', :defaults => { :format => 'json' }
  end

  root 'home#index'


end

app/models/real_estate.rb
class RealEstate < ActiveRecord::Base
  before_save :clear_not_number
  before_validation :clear_not_number

  belongs_to :neighborhood
  belongs_to :user_changed_by, :class_name => 'User'

  has_many :real_estate_images
  accepts_nested_attributes_for :real_estate_images, :reject_if => lambda { |a| a[:url].blank? }

  enum rent_type: {:apartment => 0, :home => 1, :land => 2, :release => 3, :loft => 4, :studio => 5, :store_business => 6,  :room_store => 7, :business_center => 8, :warehouse => 9, :coverage => 10, :duplex => 11}
  enum conservation: {:perfect => 0, :needs_reform => 1}
  enum furnished: {:yes => 0, :no => 1, :half => 2}

  validates :title, length: {maximum: 100}, allow_nil: false, allow_blank: false
  validates_presence_of :price, :notes, :latitude, :neighborhood_id
  validates :street, length: {maximum: 100}, allow_nil: false, allow_blank: false

  validates :street_number, numericality: { only_integer: false, :greater_than_or_equal => 0}, :allow_nil => true
  validates :total_area, numericality: { only_integer: false, :greater_than_or_equal => 0}, :allow_nil => true
  validates :area_usable, numericality: { only_integer: false, :greater_than_or_equal => 0}, :allow_nil => true
  validates :bathrooms, numericality: { only_integer: false, :greater_than_or_equal => 0}, :allow_nil => true
  validates :bedrooms, numericality: { only_integer: false, :greater_than_or_equal => 0}, :allow_nil => true
  validates :parking_spaces, numericality: { only_integer: false, :greater_than_or_equal => 0}, :allow_nil => true


  scope :search, -> (code, text, priceIni, priceEnd)  {
    w = joins(:neighborhood => [:city => :state]).includes(:neighborhood => [:city => :state]).includes(:real_estate_images).where('real_estates.removed = ?' , false)


    if code.nil? or code.blank?
      unless text.nil? or text.blank?
        w = w.where('real_estates.title like :text or real_estates.notes like :text or real_estates.street like :text or neighborhoods.name like :text or real_states.inside_description like :text or real_states.owner_name like :text', {:text => "%#{text}%"})
      end

      unless priceIni.nil? or priceIni.blank?
        w = w.where('real_estates.price >= ?', priceIni)
      end

      unless priceEnd.nil? or priceEnd.blank?
        w = w.where('real_estates.price <= ?', priceEnd)
      end
    else
      w = w.where(:id => code.gsub(/\D+/, '').to_i)
    end

    w
  }
  scope :total_by_type, ->  {
    where('real_estates.removed = ?' , false).group(:rent_type).count
  }

  scope :search_portal, -> (bairros, type, min_price, max_price, bedrooms, bathrooms, space_vacations)  {
    w = joins(:neighborhood => [:city => :state]).includes(:real_estate_images).where('real_estates.removed = ?' , false)

    unless bairros.nil? or bairros.blank?
      w = w.where('real_estates.neighborhood_id in (?)', bairros.split(','))
    end

    unless type.nil? or type.blank?
      types = type.split(',')
      filter = []

      types.each do |t|
        filter << rent_types[t]
      end

      w = w.where('real_estates.rent_type in (?)', filter)
    end

    unless min_price.nil? or min_price.blank?
      w = w.where('real_estates.price >= ?', min_price.gsub(/\D/, ''))
    end

    unless max_price.nil? or max_price.blank?
      w = w.where('real_estates.price <= ?', max_price)
    end

    unless bedrooms.nil? or bedrooms.blank?
      w = w.where('real_estates.bedrooms in (?)', bedrooms.split(','))
    end

    unless bathrooms.nil? or bathrooms.blank?
      w = w.where('real_estates.bathrooms in (?)', bathrooms.split(','))
    end

    unless space_vacations.nil? or space_vacations.blank?
      w = w.where('real_estates.parking_spaces in (?)', space_vacations.split(','))
    end

    w
  }

  scope :last_added, -> (limit = 4)  {
    joins(:neighborhood => [:city => :state]).where('removed = ?' , false).order('id desc').limit(limit)
  }

  def code
    I18n.t("real_estate_type_#{self.rent_type}")[0..1].upcase + ('%06d' % self.id)
  end


  protected
  def clear_not_number
    self.owner_cpf = owner_cpf.gsub(/\D+/, '') unless owner_cpf.nil?
    self.owner_rg = owner_rg.gsub(/\D+/, '') unless owner_rg.nil?
    self.owner_phone = owner_phone.gsub(/\D+/, '') unless owner_phone.nil?

    self.bookie_phone = bookie_phone.gsub(/\D+/, '') unless bookie_phone.nil?
  end

  # def generate_number
  #   last = RealEstate.select('code').where('id = (select max(id) from real_estates)').lock(true).first
  #   tp = I18n.t("real_estate_type_#{self.rent_type}")[0..1].upcase
  #
  #   if last.nil?
  #     self.code = "#{tp + '000001'}"
  #   else
  #     self.code = tp + ('%06d' % (last.code.gsub(/[^0-9]/, '').to_i + 1))
  #   end
  # end



end

app/controllers/real_estates_controller.rb
class RealEstatesController < ApplicationController
  before_action :require_authentication
  before_action :set_user_session
  before_action :require_admin_permission, only: [:update, :destroy, :create, :delete_pic, :upload_pic]
  before_action :set_real_estate, only: [:edit, :show, :update, :destroy]
  after_action :expire_caches, only: [:update, :create, :destroy, :delete_pic, :upload_pic]

  layout 'manager'

  include ActionView::Helpers::NumberHelper
  include ApplicationHelper

  # S3_ACCESS_KEY_ID = 'AKIAIE7MET2SKDNYZRSQ'
  # S3_ACCESS_KEY = 'dh/LIeFpo8oKLhRh+iVpJMu6KrkY331EiQal3Aul'
  # BUY_IMOVEIS_BUCKET = 'buy-imoveis-imgs'

  S3_ACCESS_KEY_ID = 'AKIAIUEILIZQ3AZYHQAA'
  S3_ACCESS_KEY = 'L6MySa2KL3XUKiqJK6nttaVNyA0Wxld1jbQ3irwE'
  BUY_IMOVEIS_BUCKET = 'buyimoveis-imgs'

  # GET /real_estates
  def index

    respond_to do |f|
      f.html { render :layout => params[:l].nil? }
      f.json {
        @real_estates = RealEstate.search(params[:code], params[:key_word], params[:start_price].to_s.gsub('.', '').gsub(',', '.'), params[:end_price].to_s.gsub('.', '').gsub(',', '.')).paginate(:page => params[:page], :per_page => 15).order('real_estates.updated_at desc, real_estates.id desc')

        render 'index'
      }
    end
  end


  def upload_pic
    s3 = AWS::S3.new(:access_key_id => S3_ACCESS_KEY_ID, :secret_access_key => S3_ACCESS_KEY)
    key = params[:file].original_filename
    label = params[:label]

    if /(.*)\.(.*)$/ =~ key

      sec = SecureRandom.hex(4)
      if label.nil? or label.blank?
        key = "#{sanitize_url($1)}-#{sec}.#{$2}"
      else
        key = "#{sanitize_url(label)}-#{sec}.#{$2}"
      end
    end

    s3.buckets[BUY_IMOVEIS_BUCKET].objects[key].write(:file => params[:file], :acl => :public_read, :cache_control => 'Public, max-age=315360000', :expires => (Time.now + 365.days).httpdate)


    render :json => {:key => key, :label => label, :url => s3.buckets[BUY_IMOVEIS_BUCKET].objects[key].public_url.to_s}
  end

  def delete_pic
    s3 = AWS::S3.new(:access_key_id => S3_ACCESS_KEY_ID, :secret_access_key => S3_ACCESS_KEY)
    key = "#{params[:key]}.#{params[:format]}"
    s3.buckets[BUY_IMOVEIS_BUCKET].objects[key].delete

    RealEstateImage.delete_all(['url like ?', "%#{key}"])

    render :json => {}
  end

  # GET /real_estates/1
  def show
    render 'show'
  end

  # GET /real_estates/new
  def new
    @real_estate = RealEstate.new
    render :layout => params[:l].nil?
  end

  # GET /real_estates/1/edit
  def edit
    respond_to do |f|
      f.html { render :layout => params[:l].nil? }
      f.json {
        set_real_estate
        render 'show'
      }
    end
  end

  # POST /real_estates
  def create
    @real_estate = RealEstate.new(real_estate_params)
    @real_estate.user_created_by_id = @user_session.id

    respond_to do |f|
      if @real_estate.save
        f.html { redirect_to @real_estate, notice: 'Imóvel criado com sucesso.' }
        f.json { render 'show' }
      else
        f.html { render :new }
        f.json { render json: @real_estate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /real_estates/1
  def update
    @real_estate.user_changed_by_id = @user_session.id

    respond_to do |f|
      if @real_estate.update(real_estate_params)
        f.html { redirect_to @real_estate, notice: 'Imóvel alterado com sucesso.' }
        f.json { render 'show' }
      else
        f.html { render :edit }
        f.json { render json: @real_estate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /real_estates/1
  def destroy
    @real_estate.update({:removed => true, :user_changed_by_id => @user_session.id})

    respond_to do |f|
      f.html { redirect_to customers_url, notice: 'Imóvel removido com sucesso.' }
      f.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_real_estate
    @real_estate = RealEstate.includes(:real_estate_images).joins(:neighborhood => [:city => :state]).find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def real_estate_params
    p = params.require(:real_estate).permit(:title, :rent_type, :latitude, :longitude, :postal_code, :neighborhood_id, :street,
                                            :street_number, :street_notes, :apartment_complex, :barbecue_grill, :concierge, :elevator, :fireplace, :planned_neighborhood,
                                            :suite, :lavatory, :vacancy, :hot_water, :central_gas, :barbecue_condo, :anchor_to_split,
                                            :anchor_to_hood, :forest, :intercom, :individual_measurement_gas, :individual_measurement_water, :vacancy_guest,
                                            :port_cochare, :party_room, :terrace, :room_convention, :gourmet_space, :adult_pool, :children_pool, :gym,
                                            :pantry, :dressing, :dependence_maid, :tv_circuit, :automatization, :generator,
                                            :garth, :balcony, :service_area, :caretaker, :whirlpool, :lobby,
                                            :playground, :price, :apartment_complex_price, :total_area, :area_usable, :bathrooms,
                                            :solar_north, :solar_south, :solar_east, :solar_west, :position_back, :position_front, :negotiable, :busy, :exclusivity, :construction_company,
                                            :ground_type, :service, :inside_description, :owner_name, :owner_rg, :owner_cpf, :owner_phone, :owner_email, :bookie_name,
                                            :bookie_email, :bookie_phone, :bookie_where_keys, :square_meter_value, :brokerage_value, :iptu_value, :front_meters,
                                            :back_meters, :construtive_index, :enrollment_number, :enrollment_vacation_number, :registration_zone, :elevators, :rooms,
                                            :balconies, :kitchens, :year_construction, :conservation,
                                            :furnished, :towers_count, :apartment_floor_count,
                                            :floor_count, :apartment_count, :vacancy_covered, :vacancy_uncovered, :vacancy_double, :vacancy_simple,
                                            :bedrooms, :parking_spaces, :notes, real_estate_images_attributes: [:id, :url, :label])
    p[:price] = p[:price].to_s.gsub('.', '').gsub(',', '.')
    p[:apartment_complex_price] = p[:apartment_complex_price].to_s.gsub('.', '').gsub(',', '.')
    p[:square_meter_value] = p[:square_meter_value].to_s.gsub('.', '').gsub(',', '.')
    p[:brokerage_value] = p[:brokerage_value].to_s.gsub('.', '').gsub(',', '.')
    p[:iptu_value] = p[:iptu_value].to_s.gsub('.', '').gsub(',', '.')

    p
  end

  def expire_caches
    expire_fragment('general_real_estates')
    expire_fragment('general_real_estates_home')
  end
end

app/helpers/real_estates_helper.rb
module RealEstatesHelper
end

app/views/real_estates/_address.html.erb
<div class="row">
  <div class="col-xs-12">
    <h5>Marque o local no mapa</h5>

    <div class="form-group">
      <input id="placeSearch" class="form-control" type="search" placeholder="Procurar localidade...">
    </div>
    <div class="clearfix"></div>

    <div class="container-fluid" id="divGmap" style="min-height: 350px"></div>
  </div>
</div>

<div class="row" style="margin-top: 10px">
  <div class="form-group col-sm-2">
    <label for="postalCode">CEP</label>
    <input type="text" ng-model="entity.postalCode" data-ng-keyup="searchPostalCode($event)" class="form-control" id="postalCode" name="postalCode" placeholder="Informe o CEP">
  </div>

  <div class="form-group col-sm-10" ng-class="{'has-error': form.neighborhood.$error.required && form.neighborhood.$dirty}">
    <label for="neighborhoodText">Bairro</label>
    <input type="text" ng-model="neighborhoodText" class="form-control" id="neighborhoodText" name="neighborhoodText" placeholder="Informe o bairro">
    <a class="text-gradient-info-lt" href="#" onclick="$('#neighborhoodText').val('indepe, porto a').trigger('keydown')">Clique aqui pra ver um exemplo...</a>
  </div>
</div>
<div class="row">
  <div class="form-group col-sm-8" ng-class="{'has-error': form.street.$error.required && form.street.$dirty}">
    <label for="street">Endereço <span class="text-gradient-danger">*</span></label>
    <input type="text" ng-model="entity.street" class="form-control" id="street" name="street" placeholder="Informe o endereço" required>
  </div>
  <div class="form-group col-sm-2">
    <label for="streetNotes">Complemento</label>
    <input type="text" maxlength="30" ng-model="entity.streetNotes" class="form-control text-right" id="streetNotes" name="streetNotes" placeholder="Complemento">
  </div>
  <div class="form-group col-sm-2" ng-class="{'has-error': form.streetNumber.$error.pattern  && form.streetNumber.$dirty}">
    <label for="streetNumber">Número</label>
    <input type="text" ng-pattern="/^\d{0,10}$/" min="0" maxlength="10" ng-model="entity.streetNumber" class="form-control text-right" id="streetNumber" name="streetNumber" placeholder="Informe o número">
  </div>
</div>

app/views/real_estates/_bookie_data.html.erb
<div class="row">
  <div class="form-group col-sm-3">
    <label for="bookieName">Nome Proprietário</label>
    <input type="text" ng-model="entity.bookieName" class="form-control" id="bookieName" name="bookieName" placeholder="Informe o nome">
  </div>
  <div class="form-group col-sm-2">
    <label for="phone">Telefone</label>
    <input type="text" ng-model="entity.bookiePhone" input-mask="{mask: '?(99) 9999-999999'}" class="form-control" id="phone" name="phone" placeholder="Informe o telefone">
  </div>
  <div class="form-group col-sm-3" ng-class="{'has-error': form.bookieEmail.$error.email && form.bookieEmail.$dirty}">
    <label for="bookieEmail">E-mail</label>
    <input type="text" ng-model="entity.bookieEmail" class="form-control" id="bookieEmail" name="bookieEmail" placeholder="Informe o e-mail">
  </div>

  <div class="form-group col-sm-4">
    <label for="bookieWhereKeys">Local da(s) Chave(s)</label>
    <input type="text" ng-model="entity.bookieWhereKeys" class="form-control" id="bookieWhereKeys" name="bookieWhereKeys" placeholder="Informe o local da(s) chave(s)">
  </div>
</div>

app/views/real_estates/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6">
      <h3 class="em-page-header v-mid-row thin">
        <i class="icm icm-home6 text-gradient-info-dk"></i>
        <span class="text-gradient-info-dk">Imóveis</span>
      </h3>
    </div>
    <div class="col-sm-6 text-right-sm text-right-md text-right-lg hidden-xs hidden-sm">
      <ul class="breadcrumb breadcrumb-top">
        <li><i class="fa fa-home"></i> Manager</li>
        <li class="active">Imóveis</li>
      </ul>
    </div>
  </div>
</div>
<div class="container-fluid">
  <form id="form" name="form" role="form" ng-submit="save(entity)">

    <h4 ng-if="entity.id" class="text-right">Criado em: <span style="font-weight: bold" ng-bind="entity.createdAt"></span> | Última alteração: <span style="font-weight: bold" ng-bind="entity.updatedAt"></span> | Quem alterou: <span style="font-weight: bold" ng-bind="entity.userChangedBy.name"></span></h4>
    <div class="rows">
      <ul class="nav nav-tabs nav-justified-only">
        <li class="active">
          <a href="#generalDataTab" target="_self" data-toggle="tab">Informações Gerais</a>
        </li>
        <li>
          <a href="#addressDataTab" ng-click="redrawMap()" target="_self" data-toggle="tab">Endereço</a>
        </li>
        <li>
          <a href="#caracteristicsDataTab" target="_self" data-toggle="tab">Dados do Imóvel</a>
        </li>
        <li>
          <a href="#ownerDataTab" target="_self" data-toggle="tab">Dados do Proprietário</a>
        </li>
        <li>
          <a href="#bookieDataTab" target="_self" data-toggle="tab">Dados do Agenciador</a>
        </li>
      </ul>
      <div class="tab-content bg-white padded margin-bottom">
        <div id="generalDataTab" class="tab-pane fade in active">
          <%= render :partial => 'general_data' %>
        </div>
        <div id="addressDataTab" class="tab-pane fade in">
          <%= render :partial => 'address' %>
        </div>
        <div id="caracteristicsDataTab" class="tab-pane fade in">
          <%= render :partial => 'properties' %>
        </div>
        <div id="ownerDataTab" class="tab-pane fade in">
          <%= render :partial => 'owner_data' %>
        </div>
        <div id="bookieDataTab" class="tab-pane fade in">
          <%= render :partial => 'bookie_data' %>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
        <div class="pull-right">
          <a class="btn btn-dark" href="<%= real_estates_path %>"><i class="fa fa-arrow-left"></i><span class="hidden-xs">  Voltar</span></a>
          <button type="button" ng-click="resetSaveForm(form)" class="btn btn-dark"><i class="fa fa-refresh"></i><span class="hidden-xs">  Limpar</span></button>
          <a href="<%= new_proposal_path %>?by={{entity.id}}" ng-hide="entity.id === undefined" class="btn btn-dark"><i class="fa fa-file-archive-o"></i><span class="hidden-xs">  Criar Proposta</span></a>
          <button type="submit" ng-disabled="form.$invalid" class="btn btn-primary"><i class="fa fa-save"></i><span class="hidden-xs">  Salvar</span></button>
        </div>
        <div class="clearfix"></div>
        <br/>
      </div>
    </div>
  </form>

</div>

app/views/real_estates/edit.html.erb
<%= render 'form' %>

app/views/real_estates/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6">
      <h3 class="em-page-header v-mid-row thin">
        <i class="icm icm-home6 text-gradient-info-dk"></i>
        <span class="text-gradient-info-dk">Pesquisa de Imóveis</span>
      </h3>
    </div>
    <div class="col-xs-6 text-right-sm text-right-md text-right-lg hidden-xs hidden-sm">
      <ul class="breadcrumb breadcrumb-top">
        <li><i class="fa fa-home"></i> Manager</li>
        <li class="active">Pesquisa de Imóveis</li>
      </ul>
    </div>
  </div>
</div>


<div class="container-fluid">
  <div class="container-fluid">
    <div class="rows" rel="panels">
      <div class="panels">
        <div class="panel panel-default gradient-diag1">
          <div class="panel-heading panel-handle panel-colorize">
            <div class="panel-actions pull-right panel-actions-reveal">
            <span class="panel-actions-reveal-hide animated fadeInRight">
                <span class="panel-action panel-fullscreen">
                  <i class="fa fa-expand"></i>
                </span>
                <span class="panel-action panel-collapse">
                  <i class="fa fa-minus"></i>
                </span>
            </span>
              &nbsp;&nbsp;
              <i class="fa fa-bars panel-actions-reveal-icon"></i>
            </div>
            <div class="panel-title">
              <span class="panel-title">Dados da pesquisa</span>
            </div>
          </div>
          <div class="panel-body-collapse collapse in">
            <div class="panel-body">
              <form id="form" name="form" role="form" ng-submit="search()">

                <div class="form-group col-sm-2">
                  <label for="code">Código</label>
                  <input type="text" ng-model="searchParams.code" maxlength="11" class="form-control" id="code" name="code" placeholder="Informe o código">
                </div>

                <div class="form-group col-sm-10">
                  <label for="keyWord">O que procura</label>
                  <input type="text" ng-model="searchParams.keyWord" maxlength="100" class="form-control" id="keyWord" name="keyWord" placeholder="Informe o que procura (títulos, descrição, endereço ou bairro)">
                </div>

                <div class="form-group col-sm-4">
                  <label for="startPrice">Preço inicial</label>
                  <input type="text" ng-model="searchParams.startPrice" class="form-control text-right" id="startPrice" name="startPrice" placeholder="Início" data-affixes-stay="true" data-thousands="." data-decimal=",">
                </div>
                <div class="form-group col-sm-4">
                  <label for="endPrice">Preço final</label>
                  <input type="text" ng-model="searchParams.endPrice" class="form-control text-right" id="endPrice" name="endPrice" placeholder="Fim" data-affixes-stay="true" data-thousands="." data-decimal=",">
                </div>

                <div class="clearfix"></div>

                <div class="pull-right">
                  <button type="button" ng-click="resetSearchForm()" class="btn btn-default"><i class="fa fa-refresh"></i><span class="hidden-xs">  Limpar</span></button>
                  <a class="btn btn-info" href="<%= new_real_estate_path %>"><i class="fa fa-plus"></i><span class="hidden-xs">  Incluir</span></a>
                  <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i><span class="hidden-xs">  Pesquisar</span></button>
                </div>
                <div class="clearfix"></div>
                <br/>
              </form>
              <hr/>
              <paging class="small"
                      page="results.currentPage"
                      page-size="results.perPage"
                      total="results.totalEntries"
                      adjacent="1"
                      hide-if-empty="false"
                      ul-class="pagination pagination-sm"
                      show-prev-next="true"
                      paging-action="paginate(page)"></paging>

              <table class="table table-clean table-bordered datatable" data-scroll=".oc-scroll" id="rid690039f4aa0432318fd14c6e6bd1ea8512">
                <thead>
                <tr>
                  <th class="text-center">Código</th>
                  <th class="text-center">Título</th>
                  <th class="text-center hidden-xs">Bairro/Cidade</th>
                  <th class="text-center hidden-xs">Tipo</th>
                  <th class="text-center hidden-xs">Preço</th>
                  <th style="min-width: 110px"></th>
                </tr>
                </thead>
                <tbody>
                <tr ng-repeat="e in results.entries">
                  <td class="text-center">{{e.code}}</td>
                  <td class="text-center">{{e.title}}</td>
                  <td class="text-left hidden-xs">{{e.neighborhoodName}}/{{e.cityName}}</td>
                  <td class="text-center hidden-xs">{{e.type}}</td>
                  <td class="text-right hidden-xs">{{e.price}}</td>
                  <td class="text-center">
                    <div class="btn-group">
                      <a href="/manager/real_estates/{{e.id}}/edit" title="Editar" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
                      <a href="<%= new_proposal_path %>?by={{e.id}}" title="Criar Proposta" class="btn btn-info btn-sm"><i class="fa fa-file-archive-o"></i></a>
                      <a href="#" ng-click="destroy(e)" title="Remover" class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></a>
                    </div>
                  </td>
                </tr>
                </tbody>
              </table>
              <paging class="small"
                      page="results.currentPage"
                      page-size="results.perPage"
                      total="results.totalEntries"
                      adjacent="1"
                      hide-if-empty="false"
                      ul-class="pagination pagination-sm"
                      show-prev-next="true"
                      paging-action="paginate(page)"></paging>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/real_estates/new.html.erb
<%= render 'form' %>

app/views/real_estates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Notes:</strong>
  <%= @real_estate.notes %>
</p>

<%= link_to 'Edit', edit_real_estate_path(@real_estate) %> |
<%= link_to 'Back', real_estates_path %>