config/routes.rb
Rails.application.routes.draw do

  get 'sitemap.:format' => 'home#sitemap'

  get 'sobre' => 'about_us#index', :as => 'about_us'
  get 'contato' => 'contact#index', :as => 'contact'
  post 'contato' => 'contact#contact_us', :as => 'contact_us'

  get 'imovel/:id/:estate/:city/:title' => 'look_real_estate#index', :as => 'look_real_estate_index'
  get 'imovel/codigo/:code' => 'look_real_estate#by_code', :as => 'look_real_estate_index_code'
  get 'imovel/proposta/:key' => 'look_real_estate#proposal', :as => 'look_real_estate_proposal'
  post 'imovel/solicitar-proposta' => 'look_real_estate#call_proposal', :as => 'look_real_estate_call_proposal'

  get 'procurar' => 'search#index', :as => 'search'
  get 'procurar/tipo/:name/:page' => 'search#type', :as => 'search_by_type'

  get 'locations/all-states' => 'application#load_states'
  get 'locations/search-cities/:state_id' => 'application#search_cities'
  get 'locations/search-cities-by-name/:q' => 'application#search_cities_by_name'
  get 'locations/search-neighborhoods/:q' => 'application#search_neighborhoods'
  get 'locations/search-neighborhoods-by-city/:city_id' => 'application#search_neighborhoods_by_city'
  get 'locations/search-postal-code/:postal_code' => 'application#search_postal_code'
  post 'news-letter/subscribe' => 'news_letters#subscribe', :as => 'subscribe'


  get 'manager' => 'manager_home#index'

  scope :manager do
    resources :real_estates do
      collection do
        post 'upload-pic', :to => 'real_estates#upload_pic', :as => 'upload_pic'
        delete 'delete-pic/:key', :to => 'real_estates#delete_pic', :as => 'delete_pic'
      end
    end

    resources :users do
      collection do
        get 'profile', :to => 'users#profile', :as => 'profile'
      end
    end

    resources :proposals do
      collection do
        get 'real-estate/:id', :to => 'proposals#real_estate', :as => 'real_estate'
        get 'send-proposal/:id', :to => 'proposals#send_proposal', :as => 'send_proposal'
      end
    end

    resources :cities, :neighborhoods, :news_letters

    get 'session' => 'session#index'
    post 'session/create' => 'session#create'
    get 'session/destroy' => 'session#destroy'
    post 'session/forget-password' => 'session#forget_password', :defaults => { :format => 'json' }
  end

  root 'home#index'


end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  belongs_to :real_estate

  before_create :generate_number


  validates :email, format: {:with => /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/}


  scope :search, -> (code, real_estate_code, text) {
    w = joins(:real_estate).where('proposals.removed = ?', false)


    if (code.nil? || code.blank?) and (real_estate_code.nil? or real_estate_code.blank?)
      unless text.nil? or text.blank?
        w = w.where('notes like :text', {:text => "%#{text}%"})
      end
    else
      if !code.nil? and !code.blank?
        w = w.where('proposals.code = ?', code)
      else
        w = w.where('real_estates.code = ?', real_estate_code)
      end
    end

    w
  }


  protected
  def generate_number
    self.key = SecureRandom.hex

    last = Proposal.select('code, created_at').where('id = (select max(id) from proposals)').lock(true).first
    current_date = Date.current

    if last.nil? || current_date.year > last.created_at.year
      self.code = "#{current_date.strftime('%Y%m') + '00001'}".to_i
    else
      self.code = last.code.to_i + 1
    end
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :require_authentication
  before_action :set_user_session
  before_action :set_proposal, only: [:edit, :update, :destroy, :show, :send_proposal]

  layout 'manager'

  # GET /proposals
  def index
    respond_to do |f|
      f.html { render :layout => params[:l].nil? }
      f.json {

        @proposals = Proposal.search(params[:code], params[:real_estate_code], params[:key_word]).paginate(:page => params[:page], :per_page => 15).order('id desc')

        render :json => {
                   :current_page => @proposals.current_page,
                   :per_page => @proposals.per_page,
                   :total_entries => @proposals.total_entries,
                   :entries => @proposals.map{|p| {:id => p.id, :email => p.email, :code => p.code, :real_estate_id => p.real_estate_id, :realEstate => {:code => p.real_estate.code, :title => p.real_estate.title}}}
               }
      }
    end
  end

  def send_proposal
    GeneralNotifier.send_proposal(@proposal, @user_session.email).deliver
    render :json => {}
  end

  def real_estate
    re = RealEstate.find params[:id]
    render :json => {:id => re.id, :code => re.code, :notes => re.notes}
  end

  # GET /proposals/1
  def show
    render :json => {:id => @proposal.id, :code => @proposal.code, :email => @proposal.email, :notes => @proposal.notes, :real_estate => {:id => @proposal.real_estate_id, :code => @proposal.real_estate.code, :notes => @proposal.real_estate.notes}}
  end

  # GET /proposals/new
  def new
    render :layout => params[:l].nil?
  end

  # GET /proposals/1/edit
  def edit
    respond_to do |f|
      f.html { render :layout => params[:l].nil? }
      f.json {
        set_proposal
        render :json => @proposal
      }
    end
  end

  # POST /proposals
  def create
    @proposal = Proposal.new(proposal_params)
    @proposal.user_created_by_id = @user_session.id

    respond_to do |f|
      if @proposal.save
        f.html { redirect_to @proposal, notice: 'Proposta criada com sucesso.' }
        f.json { render :json => {:id => @proposal.id, :email => @proposal.email, :code => @proposal.code, :notes => @proposal.notes, :real_estate => {:id => @proposal.real_estate_id, :code => @proposal.real_estate.code, :notes => @proposal.real_estate.notes}} }
      else
        f.html { render :new }
        f.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proposals/1
  def update
    respond_to do |f|
      if @proposal.update(proposal_params)
        f.html { redirect_to @proposal, notice: 'Proposta alterada com sucesso.' }
        f.json { head :no_content }
      else
        f.html { render :edit }
        f.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1
  def destroy
    @proposal.update({:removed => true})
    respond_to do |f|
      f.html { redirect_to proposals_url, notice: 'Propostal removida com sucesso.' }
      f.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_proposal
    @proposal = Proposal.includes(:real_estate).find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def proposal_params
    params.require(:proposal).permit(:notes, :real_estate_id, :email)
  end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6">
      <h3 class="em-page-header v-mid-row thin">
        <i class="icm icm-home6 text-gradient-info-dk"></i>
        <span class="text-gradient-info-dk">Propostas</span>
      </h3>
    </div>
    <div class="col-sm-6 text-right-sm text-right-md text-right-lg hidden-xs hidden-sm">
      <ul class="breadcrumb breadcrumb-top">
        <li><i class="fa fa-home"></i> Manager</li>
        <li class="active">Propostas</li>
      </ul>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="rows" rel="panels">
    <div class="panels">
      <div class="panel panel-default gradient-diag1">
        <div class="panel-heading panel-handle panel-colorize">
          <div class="panel-actions pull-right panel-actions-reveal">
            <span class="panel-actions-reveal-hide animated fadeInRight">
                <span class="panel-action panel-fullscreen">
                  <i class="fa fa-expand"></i>
                </span>
                <span class="panel-action panel-collapse">
                  <i class="fa fa-minus"></i>
                </span>
            </span>
            &nbsp;&nbsp;
            <i class="fa fa-bars panel-actions-reveal-icon"></i>
          </div>
          <div class="panel-title">
            <span class="panel-title" data-type="text">Dados da Proposta <span ng-hide="entity.id === undefined">({{entity.code}})</span> </span>
          </div>
        </div>
        <div class="panel-body-collapse collapse in">
          <div class="panel-body">
            <form id="form" name="form" role="form" ng-submit="save(entity)">

              <div class="form-group">
                <label for="realEstatecode">Código do imóvel: <b>{{entity.realEstate.code}}</b></label>
              </div>

              <div class="form-group string">
                <label for="realEstateNotes">Dados do imóvel: <br/>{{entity.realEstate.notes}}</label>
              </div>

              <div class="form-group string">
                <label for="notes">E-mail<span class="text-gradient-danger">*</span></label>
                <input type="text" ng-model="entity.email" name="email" id="email" class="form-control" required/>
              </div>

              <div class="form-group string">
                <label for="notes">Descrição da proposta<span class="text-gradient-danger">*</span></label>
                <textarea class="form-control" id="notes" name="notes" ng-model="entity.notes" required rel="autosize" placeholder="Descrição" style="overflow: hidden; word-wrap: break-word; resize: vertical; height: 200px;"></textarea>
              </div>

              <div class="pull-right">
                <a class="btn btn-default" href="<%= proposals_path %>"><i class="fa fa-arrow-left"></i><span class="hidden-xs">  Voltar</span></a>
                <button type="button" ng-click="resetSaveForm(form)" class="btn btn-default"><i class="fa fa-refresh"></i><span class="hidden-xs">  Limpar</span></button>
                <a href="<%= real_estates_path %>" class="btn btn-default"><i class="fa fa-search"></i><span class="hidden-xs">  Procurar Imóvel</span></a>
                <button type="button" ng-show="entity.id != null" ng-click="send()" class="btn btn-default"><i class="icm icm-mail-send"></i><span class="hidden-xs">  Enviar Proposta</span></button>
                <button type="submit" ng-disabled="form.$invalid" class="btn btn-primary"><i class="fa fa-save"></i><span class="hidden-xs">  Salvar</span></button>
              </div>
              <div class="clearfix"></div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/proposals/edit.html.erb
<%= render 'form' %>

app/views/proposals/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6">
      <h3 class="em-page-header v-mid-row thin">
        <i class="icm icm-home6 text-gradient-info-dk"></i>
        <span class="text-gradient-info-dk">Pesquisa de Propostas</span>
      </h3>
    </div>
    <div class="col-xs-6 text-right-sm text-right-md text-right-lg hidden-xs hidden-sm">
      <ul class="breadcrumb breadcrumb-top">
        <li><i class="fa fa-home"></i> Manager</li>
        <li class="active">Pesquisa de Propostas</li>
      </ul>
    </div>
  </div>
</div>


<div class="container-fluid">
  <div class="container-fluid">
    <div class="rows" rel="panels">
      <div class="panels">
        <div class="panel panel-default gradient-diag1">
          <div class="panel-heading panel-handle panel-colorize">
            <div class="panel-actions pull-right panel-actions-reveal">
            <span class="panel-actions-reveal-hide animated fadeInRight">
                <span class="panel-action panel-fullscreen">
                  <i class="fa fa-expand"></i>
                </span>
                <span class="panel-action panel-collapse">
                  <i class="fa fa-minus"></i>
                </span>
            </span>
              &nbsp;&nbsp;
              <i class="fa fa-bars panel-actions-reveal-icon"></i>
            </div>
            <div class="panel-title">
              <span class="panel-title">Dados da Proposta</span>
            </div>
          </div>
          <div class="panel-body-collapse collapse in">
            <div class="panel-body">
              <form id="form" name="form" role="form" ng-submit="search()">


                <div class="form-group col-sm-2">
                  <label for="code">Código da proposta</label>
                  <input type="text" ng-model="searchParams.code" maxlength="15" class="form-control" id="code" name="code" placeholder="Informe o código da proposta">
                </div>
                <div class="form-group col-sm-2">
                  <label for="realEstateCode">Código do imóvel</label>
                  <input type="text" ng-model="searchParams.realEstateCode" maxlength="15" class="form-control" id="realEstateCode" name="realEstateCode" placeholder="Informe o código do imóvel">
                </div>

                <div class="form-group col-sm-12">
                  <label for="keyWord">Descrição</label>
                  <input type="text" ng-model="searchParams.keyWord" maxlength="100" class="form-control" id="keyWord" name="keyWord" placeholder="Informe o que procura (descrição)">
                </div>

                <div class="clearfix"></div>

                <div class="pull-right">
                  <button type="button" ng-click="resetSearchForm()" class="btn btn-default"><i class="fa fa-refresh"></i><span class="hidden-xs">  Limpar</span></button>
                  <a class="btn btn-info" href="<%= new_proposal_path %>"><i class="fa fa-plus"></i><span class="hidden-xs">  Incluir</span></a>
                  <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i><span class="hidden-xs">  Pesquisar</span></button>
                </div>
                <div class="clearfix"></div>
                <br/>
              </form>
              <hr/>
              <paging class="small"
                      page="results.currentPage"
                      page-size="results.perPage"
                      total="results.totalEntries"
                      adjacent="1"
                      hide-if-empty="false"
                      ul-class="pagination pagination-sm"
                      show-prev-next="true"
                      paging-action="paginate(page)"></paging>

              <table class="table table-clean table-bordered datatable" data-scroll=".oc-scroll" id="rid690039f4aa0432318fd14c6e6bd1ea8512">
                <thead>
                <tr>
                  <th class="text-center">Código da Proposta</th>
                  <th class="text-center">Título Anúncio</th>
                  <th class="text-center">E-mail</th>
                  <th class=""></th>
                </tr>
                </thead>
                <tbody>
                <tr ng-repeat="e in results.entries">
                  <td class="text-center">{{e.code}}</td>
                  <td class="text-left"><a href="/manager/real_estates/{{e.realEstateId}}/edit">{{e.realEstate.title}}</a></td>
                  <td class="text-center"><a href="mailto:{{e.email}}" target="_blank">{{e.email}}</a></td>
                  <td class="text-center">
                    <div class="btn-group">
                      <a href="/manager/proposals/{{e.id}}/edit" title="Editar" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
                      <a href="#" ng-click="destroy(e)" title="Remover" class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></a>
                    </div>
                  </td>
                </tr>
                </tbody>
              </table>
              <paging class="small"
                      page="results.currentPage"
                      page-size="results.perPage"
                      total="results.totalEntries"
                      adjacent="1"
                      hide-if-empty="false"
                      ul-class="pagination pagination-sm"
                      show-prev-next="true"
                      paging-action="paginate(page)"></paging>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/proposals/new.html.erb
<%= render 'form' %>

app/views/proposals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Notes:</strong>
  <%= @proposal.notes %>
</p>

<%= link_to 'Edit', edit_proposal_path(@proposal) %> |
<%= link_to 'Back', proposals_path %>