config/routes.rb
Rails.application.routes.draw do

  get 'sitemap.:format' => 'home#sitemap'

  get 'sobre' => 'about_us#index', :as => 'about_us'
  get 'contato' => 'contact#index', :as => 'contact'
  post 'contato' => 'contact#contact_us', :as => 'contact_us'

  get 'imovel/:id/:estate/:city/:title' => 'look_real_estate#index', :as => 'look_real_estate_index'
  get 'imovel/codigo/:code' => 'look_real_estate#by_code', :as => 'look_real_estate_index_code'
  get 'imovel/proposta/:key' => 'look_real_estate#proposal', :as => 'look_real_estate_proposal'
  post 'imovel/solicitar-proposta' => 'look_real_estate#call_proposal', :as => 'look_real_estate_call_proposal'

  get 'procurar' => 'search#index', :as => 'search'
  get 'procurar/tipo/:name/:page' => 'search#type', :as => 'search_by_type'

  get 'locations/all-states' => 'application#load_states'
  get 'locations/search-cities/:state_id' => 'application#search_cities'
  get 'locations/search-cities-by-name/:q' => 'application#search_cities_by_name'
  get 'locations/search-neighborhoods/:q' => 'application#search_neighborhoods'
  get 'locations/search-neighborhoods-by-city/:city_id' => 'application#search_neighborhoods_by_city'
  get 'locations/search-postal-code/:postal_code' => 'application#search_postal_code'
  post 'news-letter/subscribe' => 'news_letters#subscribe', :as => 'subscribe'


  get 'manager' => 'manager_home#index'

  scope :manager do
    resources :real_estates do
      collection do
        post 'upload-pic', :to => 'real_estates#upload_pic', :as => 'upload_pic'
        delete 'delete-pic/:key', :to => 'real_estates#delete_pic', :as => 'delete_pic'
      end
    end

    resources :users do
      collection do
        get 'profile', :to => 'users#profile', :as => 'profile'
      end
    end

    resources :proposals do
      collection do
        get 'real-estate/:id', :to => 'proposals#real_estate', :as => 'real_estate'
        get 'send-proposal/:id', :to => 'proposals#send_proposal', :as => 'send_proposal'
      end
    end

    resources :cities, :neighborhoods, :news_letters

    get 'session' => 'session#index'
    post 'session/create' => 'session#create'
    get 'session/destroy' => 'session#destroy'
    post 'session/forget-password' => 'session#forget_password', :defaults => { :format => 'json' }
  end

  root 'home#index'


end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  belongs_to :city
  has_many :real_estates

  validates_presence_of :name, :city_id


  scope :search, -> (text) {
    w = joins(:city => :state)

    if /,/ =~ text
      text = text.split(',')

      w = w.where('neighborhoods.name like ?', "#{text[0].strip}%")
      w = w.where('cities.name like ?', "#{text[1].strip}%") if text.length >= 2
      w = w.where('states.name like ?', "#{text[2].strip}%") if text.length == 3

    else
      unless text.nil? or text.blank?
        w = w.where('neighborhoods.name like :text or cities.name like :text or states.name like :text', {:text => "%#{text.strip}%"})
      end
    end

    w
  }

  scope :search_by_city, -> (city_id) {
    joins(:city => :state).where('neighborhoods.city_id = ? and exists (select 1 from real_estates re where re.neighborhood_id = neighborhoods.id and re.removed = ? and exists (select 1 from real_estate_images rei where rei.real_estate_id = re.id))', city_id, false).order('neighborhoods.name asc')
  }

end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  before_action :set_user_session
  before_action :require_authentication
  before_action :set_neighborhood, only: [:edit, :update, :destroy, :show]

  layout 'manager'

  # GET /neighborhoods
  def index
    respond_to do |f|
      f.html { render :layout => params[:l].nil? }
      f.json {

        @neighborhoods = Neighborhood.search(params[:key_word]).paginate(:page => params[:page], :per_page => 15).order('neighborhoods.name asc, cities.name asc, states.name asc')

        render :json => {
            :current_page => @neighborhoods.current_page,
            :per_page => @neighborhoods.per_page,
            :total_entries => @neighborhoods.total_entries,
            :entries => @neighborhoods.map{|n| {:id => n.id, :name => n.name, :cityId => n.city_id, :cityName => n.city.name, :stateName => n.city.state.name}}
        }
      }
    end

  end


  # GET /neighborhoods/1
  def show
    render :json => to_json(@neighborhood)
  end

  # GET /neighborhoods/new
  def new
    @neighborhood = Neighborhood.new
    render :layout => params[:l].nil?
  end

  # GET /neighborhoods/1/edit
  def edit
    respond_to do |f|
      f.html { render :layout => params[:l].nil? }
      f.json {
        set_neighborhood
        render :json => to_json(@neighborhood)
      }
    end
  end

  # POST /neighborhoods
  def create
    @neighborhood = Neighborhood.new(neighborhood_params)

    respond_to do |f|
      if @neighborhood.save
        f.html { redirect_to @neighborhood, notice: 'Bairro criado com sucesso.' }
        f.json { render :json => to_json(@neighborhood) }
      else
        f.html { render :new }
        f.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /neighborhoods/1
  def update
    respond_to do |f|
      if @neighborhood.update(neighborhood_params)
        f.html { redirect_to @neighborhood, notice: 'Bairro alterado com sucesso.' }
        f.json { render :show, status: :ok, location: @neighborhood }
      else
        f.html { render :edit }
        f.json { render json: @neighborhood.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /neighborhoods/1
  def destroy
    @neighborhood.destroy
    respond_to do |f|
      f.html { redirect_to neighborhoods_url, notice: 'Bairro removido com sucesso.' }
      f.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_neighborhood
      @neighborhood = Neighborhood.joins(:city => :state).find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def neighborhood_params
      params.require(:neighborhood).permit(:name, :city_id)
    end

  def to_json n
    {:id => n.id, :name => n.name, :city_id => n.city_id, :city => {:name => n.city.name, :state => {:id => n.city.state_id, :name => n.city.state.name, :acronym => n.city.state.acronym}}}
  end
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/views/neighborhoods/_form.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6">
      <h3 class="em-page-header v-mid-row thin">
        <i class="icm icm-home6 text-gradient-info-dk"></i>
        <span class="text-gradient-info-dk">Cidades</span>
      </h3>
    </div>
    <div class="col-sm-6 text-right-sm text-right-md text-right-lg hidden-xs hidden-sm">
      <ul class="breadcrumb breadcrumb-top">
        <li><i class="fa fa-home"></i> Manager</li>
        <li class="active">Bairros</li>
      </ul>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="rows" rel="panels">
    <div class="panels">
      <div class="panel panel-default gradient-diag1">
        <div class="panel-heading panel-handle panel-colorize">
          <div class="panel-actions pull-right panel-actions-reveal">
            <span class="panel-actions-reveal-hide animated fadeInRight">
                <span class="panel-action panel-fullscreen">
                  <i class="fa fa-expand"></i>
                </span>
                <span class="panel-action panel-collapse">
                  <i class="fa fa-minus"></i>
                </span>
            </span>
            &nbsp;&nbsp;
            <i class="fa fa-bars panel-actions-reveal-icon"></i>
          </div>
          <div class="panel-title">
            <span class="panel-title" data-type="text">Dados do Bairro</span>
          </div>
        </div>
        <div class="panel-body-collapse collapse in">
          <div class="panel-body">
            <form id="form" name="form" role="form" ng-submit="save(entity)">
              <div class="form-group" ng-class="{'has-error': form.name.$error.required && form.name.$dirty}">
                <label for="name">Nome <span class="text-gradient-danger">*</span></label>
                <input type="text" ng-model="entity.name" maxlength="100" class="form-control" id="name" name="name" placeholder="Informe o nome" required>
              </div>
              <div class="form-group col-sm-6">
                <label for="states">Estado</label>
                <select ng-model="entity.stateId" ng-change="loadCities()" id="states" ng-options="s.id as s.name for s in states" class="form-control" required></select>
              </div>
              <div class="form-group col-sm-6">
                <label for="city">Cidade <span class="text-gradient-danger">*</span></label>
                <select ng-model="entity.cityId" id="city" ng-options="c.id as c.name for c in cities" class="form-control" required><option style="display: none"></option></select>
              </div>

              <div class="clearfix"></div>

              <div class="pull-right">
                <a class="btn btn-default" href="<%= neighborhoods_path %>"><i class="fa fa-arrow-left"></i><span class="hidden-xs">  Voltar</span></a>
                <button type="button" ng-click="resetSaveForm(form)" class="btn btn-default"><i class="fa fa-refresh"></i><span class="hidden-xs">  Limpar</span></button>
                <button type="submit" ng-disabled="form.$invalid" class="btn btn-primary"><i class="fa fa-save"></i><span class="hidden-xs">  Salvar</span></button>
              </div>
              <div class="clearfix"></div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/neighborhoods/edit.html.erb
<%= render 'form' %>

app/views/neighborhoods/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-6">
      <h3 class="em-page-header v-mid-row thin">
        <i class="icm icm-home6 text-gradient-info-dk"></i>
        <span class="text-gradient-info-dk">Pesquisa de Bairros</span>
      </h3>
    </div>
    <div class="col-xs-6 text-right-sm text-right-md text-right-lg hidden-xs hidden-sm">
      <ul class="breadcrumb breadcrumb-top">
        <li><i class="fa fa-home"></i> Manager</li>
        <li class="active">Pesquisa de Bairros</li>
      </ul>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="container-fluid">
    <div class="rows" rel="panels">
      <div class="panels">
        <div class="panel panel-default gradient-diag1">
          <div class="panel-heading panel-handle panel-colorize">
            <div class="panel-actions pull-right panel-actions-reveal">
            <span class="panel-actions-reveal-hide animated fadeInRight">
                <span class="panel-action panel-fullscreen">
                  <i class="fa fa-expand"></i>
                </span>
                <span class="panel-action panel-collapse">
                  <i class="fa fa-minus"></i>
                </span>
            </span>
              &nbsp;&nbsp;
              <i class="fa fa-bars panel-actions-reveal-icon"></i>
            </div>
            <div class="panel-title">
              <span class="panel-title">Dados do Bairro</span>
            </div>
          </div>
          <div class="panel-body-collapse collapse in">
            <div class="panel-body">
              <form id="form" name="form" role="form" ng-submit="search()">

                <div class="form-group">
                  <label for="keyWord">Informe o que procura</label>
                  <input type="text" ng-model="searchParams.keyWord" maxlength="100" class="form-control" id="keyWord" name="keyWord" placeholder="Informe o bairro, cidade e estado separados por vírgula ou um ou outro">
                  <a class="text-gradient-info-lt" href="#" ng-click="searchParams.keyWord = 'aux, porto, rio';search()">Clique aqui pra ver um exemplo...</a>
                </div>


                <div class="clearfix"></div>

                <div class="pull-right">
                  <button type="button" ng-click="resetSearchForm()" class="btn btn-default"><i class="fa fa-refresh"></i><span class="hidden-xs">  Limpar</span></button>
                  <a class="btn btn-info" href="<%= new_neighborhood_path %>"><i class="fa fa-plus"></i><span class="hidden-xs">  Incluir</span></a>
                  <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i><span class="hidden-xs">  Pesquisar</span></button>
                </div>
                <div class="clearfix"></div>
                <br/>
              </form>
              <hr/>
              <paging class="small"
                      page="results.currentPage"
                      page-size="results.perPage"
                      total="results.totalEntries"
                      adjacent="1"
                      hide-if-empty="false"
                      ul-class="pagination pagination-sm"
                      show-prev-next="true"
                      paging-action="paginate(page)"></paging>

              <table class="table table-clean table-bordered datatable" data-scroll=".oc-scroll" id="rid690039f4aa0432318fd14c6e6bd1ea8512">
                <thead>
                <tr>
                  <th class="text-center">Nome</th>
                  <th class="text-center">Cidade</th>
                  <th class="text-center">Estado</th>
                  <th></th>
                </tr>
                </thead>
                <tbody>
                <tr ng-repeat="e in results.entries">
                  <td class="text-left">{{e.name}}</td>
                  <td class="text-left"><a href='/manager/cities/{{e.city_id}}/edit' target="_blank">{{e.cityName}}</a></td>
                  <td class="text-left">{{e.stateName}}</td>
                  <td class="text-center">
                    <div class="btn-group">
                      <a href="/manager/neighborhoods/{{e.id}}/edit" title="Editar" class="btn btn-primary btn-sm"><i class="fa fa-pencil"></i></a>
                      <a href="#" ng-click="destroy(e)" title="Remover" class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></a>
                    </div>
                  </td>
                </tr>
                </tbody>
              </table>
              <paging class="small"
                      page="results.currentPage"
                      page-size="results.perPage"
                      total="results.totalEntries"
                      adjacent="1"
                      hide-if-empty="false"
                      ul-class="pagination pagination-sm"
                      show-prev-next="true"
                      paging-action="paginate(page)"></paging>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/neighborhoods/new.html.erb
<%= render 'form' %>

app/views/neighborhoods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @neighborhood.name %>
</p>

<p>
  <strong>City:</strong>
  <%= @neighborhood.city %>
</p>

<%= link_to 'Edit', edit_neighborhood_path(@neighborhood) %> |
<%= link_to 'Back', neighborhoods_path %>